### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by jerodsanto** [jmhobbs/domain-swap#18]
Thanks for @jmhobbs for starting this and @zachleat for picking it up and running with it. I wanted one of these and was gonna write it myself when I saw you guys already have.

However, when I:
1. installed Domain Swap from the Chrome Web Store
2. Added a Domain Set with 3 domains (ones has https not sure if that matters)
3. Nothing happens

I closed/opened the tab, closed/opened Chrome. Still nothing.

Am I doing it wrong?

**Comment by jmhobbs** [comment]
It sounds like you are using protocols, which the current version can't handle it :-\

Instead of:

```
http://example.com
https://secure.example.com
```

Do:

```
example.com
secure.example.com:443
```

Not sure if the 443 trick will work, worth a try though.

**Comment by jerodsanto** [comment]
Ahh, yup that's the problem. Unfortunately, appending the 443 doesn't work for my https instance.

**Comment by jerodsanto** [comment]
Closing this as I see you have it covered in #19
