### ISSUE TITLE
Chrome marking this as corrupted extension

### ISSUE THREAD

**Issue by axar** [jmhobbs/domain-swap#22]
Chrome  says, "This extension may have been corrupted by malware" and disables the domain swap.

**Comment by jmhobbs** [comment]
What version Chrome are you running?

I could not reproduce on Canary 40.0.2176.0, or regular 37.0.2062.124.

Did you install from the web store, or as a local unpacked extension?

**Comment by axar** [comment]
Version 38.0.2125.101 beta-m (64-bit)
I installed from web store; however, i made a single line JS changed to open tabs in new window.

**Comment by jmhobbs** [comment]
Ah ha!  There's the issue.

They added code verification in 38.  So, if you look in the extension folder where you made the change, there should be a "_metadata" directory in there.  Inside that, is a "computed_hashes.json" with a bunch of cryptographic hashes for all the files in the extension.

``` json
{"file_hashes":[
    {"block_hashes":["6eNIEEnF21i7y6BGbK4Rs4KXQrbxl6Tk44DHd7+9lDg="],"block_size":4096,"path":"background.js"},
    {"block_hashes":["Q9HkJtB0TQTzGIB+Mez40Tttpteq9QKhL+QxdjK/oLI="],"block_size":4096,"path":"domain-sets.js"},
...
```

When you change a file, you change the hash, and Chrome tries to match the two.  When they don't match, it assumes that something has modified the extension (like malware) and refuses to load it.

If you want to modify the extension, you'll need to turn on developer mode, clone down the repo, and load it as an unpacked extension.  You can also just copy the extension folder somewhere else and load it unpacked from there.

Here's the Google guide for that: https://developer.chrome.com/extensions/getstarted#unpacked.
