### ISSUE TITLE
Package and release to store.

### ISSUE THREAD

**Issue by jmhobbs** [jmhobbs/domain-swap#3]
Once it's in a bit cleaner state and we have an icon.

**Comment by zachleat** [comment]
I think this is the last thing we should do before “going public.” Do you have a Google Web Store developer account?

**Comment by jmhobbs** [comment]
I do not, but I will get one real quick, I've got a couple others I could release too.

I'll ping you when I release it.

**Comment by jmhobbs** [comment]
Published! https://chrome.google.com/webstore/detail/domain-switcher/ngiiihlebepigjbefembddhdplmaghep
