### ISSUE TITLE
Doesn't need jQuery

### ISSUE THREAD

**Issue by mattdsteele** [jmhobbs/domain-swap#4]
Looks like you're using jQuery for selectors, iteration, etc. Probably not needed since you're just targeting a single standards-compliant browser. No need to bulk up the distribution!

I'll try & rewrite it in VanillaJS and put in a pull request.

**Comment by jmhobbs** [comment]
Indeed!  That would be much appreciated!

**Comment by jmhobbs** [comment]
@mattdsteele Have you started on this yet?  I was going to try and do a little refactoring, but I didn't want to create a nasty merge.

**Comment by mattdsteele** [comment]
I won't get to it until tomorrow at the earliest, go nuts!

**Comment by jmhobbs** [comment]
Finished this in d8f0c1e
